[workspace]
resolver = "2"
members = [
    "crates/domain-types",
    "crates/crypto",
    "crates/policy-engine",
    "crates/state-store",
    "crates/nft-enforcer",
    "crates/wg-tunnel",
    "crates/dashboard",
    "crates/cli",
]

[workspace.package]
version = "0.0.1"
edition = "2021"

[profile.release]
opt-level = "s"
lto = true
