#!/bin/sh /etc/rc.common

START=96
USE_PROCD=1

start_service() {
    config_load social-firewall
    config_get_bool enabled main enabled 0
    [ "$enabled" = 1 ] || return 0
    [ -x /usr/bin/sf ] || return 0

    config_get db main db /etc/kestrel/social-firewall/social-firewall.sqlite

    procd_open_instance
    procd_set_param command /usr/bin/sf --db "$db" listen
    procd_set_param respawn 3600 5 5
    procd_set_param file /etc/config/social-firewall
    procd_close_instance
}
