//! Post-apply health checks — run after `nft -f` succeeds, before the new
//! state is committed as "applied." A failing check triggers the same
//! rollback path as a failed `nft -f` itself.

use crate::{CommandRunner, CompiledFirewallPolicy, ProtectedDestinations, NFT_TABLE};
use std::time::Duration;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HealthCheckResult {
    pub ok: bool,
    pub reason: Option<String>,
}

impl HealthCheckResult {
    pub fn ok() -> Self {
        Self {
            ok: true,
            reason: None,
        }
    }
    pub fn fail(reason: impl Into<String>) -> Self {
        Self {
            ok: false,
            reason: Some(reason.into()),
        }
    }
}

pub trait HealthCheck {
    fn check(
        &self,
        runner: &dyn CommandRunner,
        compiled: &CompiledFirewallPolicy,
        protected: &ProtectedDestinations,
        timeout: Duration,
    ) -> HealthCheckResult;
}

/// Re-lists the live table after applying and checks two things: the
/// table actually exists (the apply really took effect), and — the
/// concrete, testable form of "protect management access" — no protected
/// destination string appears inside any `deny_*`/`quarantine_*` set's
/// element list in the *live* ruleset, not just our own compiled struct.
/// A bug that let a protected address leak into a deny set despite
/// `compile`'s own filtering would still be caught here, against the
/// actual applied state.
pub struct RulesetHealthCheck;

impl HealthCheck for RulesetHealthCheck {
    fn check(
        &self,
        runner: &dyn CommandRunner,
        _compiled: &CompiledFirewallPolicy,
        protected: &ProtectedDestinations,
        timeout: Duration,
    ) -> HealthCheckResult {
        let out = runner.run("nft", &["-a", "list", "table", "inet", NFT_TABLE], timeout);
        if !out.success {
            return HealthCheckResult::fail(format!(
                "post-apply `nft list table` failed: {}",
                out.stderr
            ));
        }

        let protected_strings = protected_destination_strings(protected);
        for (set_name, elements_line) in enforcement_set_elements(&out.stdout) {
            for p in &protected_strings {
                if elements_line.contains(p.as_str()) {
                    return HealthCheckResult::fail(format!(
                        "protected destination {p} found in live set {set_name}"
                    ));
                }
            }
        }

        HealthCheckResult::ok()
    }
}

fn protected_destination_strings(protected: &ProtectedDestinations) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    out.extend(protected.v4_addrs.iter().map(|a| a.to_string()));
    out.extend(protected.v4_nets.iter().map(|n| n.to_string()));
    out.extend(protected.v6_addrs.iter().map(|a| a.to_string()));
    out.extend(protected.v6_nets.iter().map(|n| n.to_string()));
    out
}

/// Walks `nft -a list table`'s plaintext output, yielding
/// `(set_name, elements_line)` for every `deny_*`/`quarantine_*` set
/// block that has an `elements = { ... }` line. Deliberately narrow
/// (tracks brace depth just well enough to know "am I inside a `set
/// deny_v4 { ... }` block"), not a general nft-syntax parser — this
/// output format is generated by the same `render_script` this crate
/// controls, so it doesn't need to handle arbitrary third-party rulesets.
fn enforcement_set_elements(output: &str) -> Vec<(String, String)> {
    let mut results = Vec::new();
    let mut current_set: Option<String> = None;

    for line in output.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("set ") {
            if let Some(name) = rest.split_whitespace().next() {
                if name.starts_with("deny_") || name.starts_with("quarantine_") {
                    current_set = Some(name.to_string());
                }
            }
        }
        if let (Some(name), true) = (&current_set, trimmed.starts_with("elements")) {
            results.push((name.clone(), trimmed.to_string()));
        }
        if trimmed == "}" {
            current_set = None;
        }
    }
    results
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::command::FakeCommandRunner;
    use crate::compile::compile;

    fn empty_compiled() -> CompiledFirewallPolicy {
        compile(&[], &ProtectedDestinations::default()).unwrap()
    }

    #[test]
    fn health_check_fails_when_list_table_fails() {
        let runner = FakeCommandRunner::new_all_success();
        runner.fail_next_matching(|p, a| p == "nft" && a.contains(&"list".to_string()));
        let result = RulesetHealthCheck.check(
            &runner,
            &empty_compiled(),
            &ProtectedDestinations::default(),
            Duration::from_secs(1),
        );
        assert!(!result.ok);
    }

    #[test]
    fn health_check_passes_on_a_clean_ruleset() {
        let runner = FakeCommandRunner::new_all_success();
        runner.set_default_stdout(
            "table inet social_firewall {\n\
             \tset deny_v4 {\n\
             \t\ttype ipv4_addr\n\
             \t\telements = { 203.0.113.9 }\n\
             \t}\n\
             }\n",
        );
        let mut protected = ProtectedDestinations::default();
        protected.v4_addrs.push("192.168.1.1".parse().unwrap());
        let result = RulesetHealthCheck.check(
            &runner,
            &empty_compiled(),
            &protected,
            Duration::from_secs(1),
        );
        assert!(result.ok);
    }

    #[test]
    fn health_check_fails_when_a_protected_address_leaked_into_a_live_deny_set() {
        let runner = FakeCommandRunner::new_all_success();
        runner.set_default_stdout(
            "table inet social_firewall {\n\
             \tset deny_v4 {\n\
             \t\ttype ipv4_addr\n\
             \t\telements = { 192.168.1.1, 203.0.113.9 }\n\
             \t}\n\
             }\n",
        );
        let mut protected = ProtectedDestinations::default();
        protected.v4_addrs.push("192.168.1.1".parse().unwrap());
        let result = RulesetHealthCheck.check(
            &runner,
            &empty_compiled(),
            &protected,
            Duration::from_secs(1),
        );
        assert!(
            !result.ok,
            "a protected address inside a live deny set must fail health check"
        );
    }

    #[test]
    fn protected_address_mentioned_outside_a_deny_set_does_not_fail() {
        // e.g. present in our own protected-accept rule/comment — only
        // membership inside a deny_*/quarantine_* set block matters.
        let runner = FakeCommandRunner::new_all_success();
        runner.set_default_stdout(
            "table inet social_firewall {\n\
             \tchain forward {\n\
             \t\tip daddr 192.168.1.1 accept comment \"social-firewall:protected\"\n\
             \t}\n\
             \tset deny_v4 {\n\
             \t\ttype ipv4_addr\n\
             \t\telements = { 203.0.113.9 }\n\
             \t}\n\
             }\n",
        );
        let mut protected = ProtectedDestinations::default();
        protected.v4_addrs.push("192.168.1.1".parse().unwrap());
        let result = RulesetHealthCheck.check(
            &runner,
            &empty_compiled(),
            &protected,
            Duration::from_secs(1),
        );
        assert!(result.ok);
    }
}
